Adding components validation in ci.yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -79,33 +79,33 @@ jobs:
           echo "========== VALIDATING STRUCTURE =========="
 
           # Main file index.html
-          [ -f "index.html" ] || (echo "❌ index.html not found" && exit 1)
-          echo "✅ index.html file check"
+          [ -f "index.html" ] || (echo "index.html not found" && exit 1)
+          echo "✓ index.html file check"
 
           # Required folders
-          [ -d "pages" ] || (echo "❌ pages folder not found" && exit 1)
-          echo "✅ pages folder check"
+          [ -d "pages" ] || (echo "pages folder not found" && exit 1)
+          echo "✓ pages folder check"
 
-          [ -d "config" ] || (echo "❌ config folder not found" && exit 1)
-          echo "✅ config folder check"
+          [ -d "config" ] || (echo "config folder not found" && exit 1)
+          echo "✓ config folder check"
 
-          [ -d "src" ] || (echo "❌ src folder not found" && exit 1)
-          echo "✅ src folder check"
+          [ -d "src" ] || (echo "src folder not found" && exit 1)
+          echo "✓ src folder check"
 
           # src subfolders
-          [ -d "src/components" ] || (echo "❌ src/components not found" && exit 1)
-          echo "✅ src/components folder check"
+          [ -d "src/components" ] || (echo "src/components not found" && exit 1)
+          echo "✓ src/components folder check"
 
-          [ -d "src/images" ] || (echo "❌ src/images not found" && exit 1)
-          echo "✅ src/images folder check"
+          [ -d "src/images" ] || (echo "src/images not found" && exit 1)
+          echo "✓ src/images folder check"
           
-          [ -d "src/scripts" ] || (echo "❌ src/scripts not found" && exit 1)
-          echo "✅ src/scripts folder check"
+          [ -d "src/scripts" ] || (echo "src/scripts not found" && exit 1)
+          echo "✓ src/scripts folder check"
           
-          [ -d "src/styles" ] || (echo "❌ src/styles not found" && exit 1)
-          echo "✅ src/styles folder check"
+          [ -d "src/styles" ] || (echo "src/styles not found" && exit 1)
+          echo "✓ src/styles folder check"
           
-          echo "✅ All File Structure cheked"
+          echo "✓ All File Structure cheked"
 
       - name: Validating script file location
         run: | 
@@ -127,3 +127,37 @@ jobs:
             echo "CSS files found outside src/styles"
             exit 1
           fi
+
+  Components-Structure-Analysis:
+    runs-on: ubuntu-latest
+    needs: [File-Structure-Analysis]
+
+    steps:
+      - name: Code Checkout
+        uses: actions/checkout@v4
+
+      - name: Validate component structure
+        run: |
+          echo "Validating components..."
+
+          for dir in src/components/*/; do
+            [ -d "$dir" ] || continue
+
+            component=$(basename "$dir")
+
+            html_file="$dir/$component.html"
+            js_file="$dir/$component.js"
+
+          if [ ! -f "$html_file" ]; then
+            echo "Missing HTML file in $component"
+            exit 1
+          fi
+
+          if [ ! -f "$js_file" ]; then
+            echo "Missing JS file in $component"
+            exit 1
+          fi
+
+            done
+
+            echo "Components Checked"
