Improving ci.yml file to include php files in 'Validating File Structure'

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -78,32 +78,36 @@ jobs:
         run: | 
           echo "========== VALIDATING STRUCTURE =========="
 
-          # Main file index.html
-          [ -f "index.html" ] || (echo "index.html not found" && exit 1)
-          echo "✓ index.html file check"
+          # Main file index
+          if [ -f "index.html" ] || [ -f "index.php" ]; then
+            echo "✓ index file check"
+          else
+            echo "index file found"
+            exit 1
+          fi
 
           # Required folders
-          [ -d "pages" ] || (echo "pages folder not found" && exit 1)
+          [ -d "pages" ] || { echo "pages folder not found"; exit 1; }
           echo "✓ pages folder check"
 
-          [ -d "config" ] || (echo "config folder not found" && exit 1)
-          echo "✓ config folder check"
+            [ -d "config" ] || { echo "config folder not found"; exit 1; }
+            echo "✓ config folder check"
 
-          [ -d "src" ] || (echo "src folder not found" && exit 1)
-          echo "✓ src folder check"
+            [ -d "src" ] || { echo "src folder not found"; exit 1; }
+            echo "✓ src folder check"
 
-          # src subfolders
-          [ -d "src/components" ] || (echo "src/components not found" && exit 1)
-          echo "✓ src/components folder check"
+            # src subfolders
+            [ -d "src/components" ] || { echo "src/components not found"; exit 1; }
+            echo "✓ src/components folder check"
 
-          [ -d "src/images" ] || (echo "src/images not found" && exit 1)
-          echo "✓ src/images folder check"
-          
-          [ -d "src/scripts" ] || (echo "src/scripts not found" && exit 1)
-          echo "✓ src/scripts folder check"
-          
-          [ -d "src/styles" ] || (echo "src/styles not found" && exit 1)
-          echo "✓ src/styles folder check"
+            [ -d "src/images" ] || { echo "src/images not found"; exit 1; }
+            echo "✓ src/images folder check"
+            
+            [ -d "src/scripts" ] || { echo "src/scripts not found"; exit 1; }
+            echo "✓ src/scripts folder check"
+            
+            [ -d "src/styles" ] || { echo "src/styles not found"; exit 1; }
+            echo "✓ src/styles folder check"
           
           echo "✓ All File Structure cheked"
 
